name: Auto Apply Bot

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Job URL'
        required: true
        type: string

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    env:
      ADDRESS: ${{ secrets.ADDRESS }}
      CITY: ${{ secrets.CITY }}
      STATE: ${{ secrets.STATE }}
      ZIP: ${{ secrets.ZIP }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager


    - name: Confirm Chrome & ChromeDriver are available
      run: |
        google-chrome --version
        chromedriver --version

    - name: Run bot
      run: |
        xvfb-run python auto_apply.py "${{ github.event.inputs.url }}"

    - name: Upload screenshot
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: browser-screenshot
        path: screenshot.png