name: Job Scraper

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:        # allows manual run

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Restore storage.json cache
      uses: actions/cache@v3
      with:
        path: storage.json
        key: storage-json

    - name: Show contents of restored storage.json
      run: |
        echo "🔍 Contents of storage.json after cache restore:"
        cat storage.json || echo "⚠️ storage.json not found"

    - name: Run script
      env:
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: python main.py

    - name: Show contents of updated storage.json
      run: |
        echo "✅ Updated storage.json:"
        cat storage.json || echo "⚠️ storage.json not found"

    - name: Save updated storage.json
      uses: actions/cache/save@v3
      with:
        path: storage.json
        key: storage-json
